### PR TITLE
Add support for High Sierra

### PR DESCRIPTION
**Pull request by jacobbednarz**
Creates a tracking PR that we can test multiple branches against a full installation and eventually merge it into `master`.

### CODE REVIEW

**Comment by jacobbednarz** [comment]
@webflo It looks like I'm getting an error related to the user resource not existing

```
Error: Could not create resources for managing Puppet's files and directories in sections [:main, :agent, :ssl]: undefined method `exists?' for nil:NilClass
Error: Could not prepare for execution: Could not create resources for managing Puppet's files and directories in sections [:main, :agent, :ssl]: undefined method `exists?' for nil:NilClass
undefined method `exists?' for nil:NilClass
```

Did you hit this with your upgrade?

**Comment by jacobbednarz** [comment]
You can see the full log output in our CI runs https://travis-ci.org/boxen/our-boxen/builds/348784028#L195

**Comment by webflo** [comment]
No, it does not ring a bell. Maybe its related to the special environment on Travis CI? I googled a little bit and it looks like a very generic error. 

https://projects.puppetlabs.com/issues/19670

**Comment by webflo** [comment]
Double check the version of the puppet gem.

**Comment by webflo** [comment]
I can use your High Sierra Branch in my local setup. But it will take a few days until i have time to do it.

**Comment by jacobbednarz** [comment]
I've been running VMs up and down all day without any luck (all fresh OS's). Based on some of the things I've found, this is an issue with the user not being found, in this case root, and I've got a feeling it could be related to System Integrity Protection but I'm not certain.

I'll keep looking.

**Pull request merged**
