### PR TITLE
Users can skip operating system check

### PR DESCRIPTION
**Pull request by Jberlinsky**
Allow users to skip the OS X version check if they choose to fend off the dragons.

### CODE REVIEW

**Comment by kevinjasker** [comment]
:+1:

**Comment by salimane** [comment]
could we merge this ASAP ?

**Comment by jacobbednarz** [comment]
Would you be able to give a little context to this change? I'm trying to think of a scenario where you'd like to skip the checks that are preventing failures further down the installation?

**Comment by Jberlinsky** [comment]
@jacobbednarz As I recall, the context was installing an OS X beta. It's been quite some time now, though.

**Comment by jacobbednarz** [comment]
Maybe a better approach to that would be to run on a feature branch and identify individual problems and fix them along the way instead of skipping the checks? From what I can see, it's only used in that one spot and adding the version would resolve the issue. Was there any other problems encountered here?

**Comment by jacobbednarz** [comment]
Have cherry picked this onto a new PR (#207) due to release bump being in this one.

**Pull request closed without merging**
