### PR TITLE
os.rb: support macOS 10.12 Sierra.

### PR DESCRIPTION
**Pull request by salimane**
Signed-off-by: Salimane Adjao Moustapha <me@salimane.com>
cc @MikeMcQuaid @jacobbednarz

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
I no longer maintain Boxen and do not have commit access any long.

**Comment by jacobbednarz** [comment]
This looks great! I've been meaning to find someone with Sierra so I could dry run Boxen. Do you have the new version installed?

**Comment by salimane** [comment]
yep I have the new version installed. ``boxen`` and ``our-boxen`` run with this version of ``boxen`` installed.

**Comment by jacobbednarz** [comment]
thanks! :cake:

**Comment by salimane** [comment]
a new release would be appreciated :)

**Comment by jacobbednarz** [comment]
done - bumped to [2.9.0](https://github.com/boxen/boxen/releases/tag/2.9.0)

**Pull request merged**
